### ISSUE TITLE
Photomaker being ignored?

### ISSUE THREAD

**Issue by NickDevoctomy** [shiimizu/ComfyUI-PhotoMaker#12]
Hi there, I'm very new to this. No idea what I've done wrong, clearly something I've missed!

I have comfyui and this custom_node installed. I clear my workspace and just drag and drop the image from your repo page onto the workspace, this creates all the nodes for me.  I then load in 3 images of me into the 'Load Image' nodes, select an XL checkpoint and press generate.

It all seems to run through and the 'Preview Image' node that displays the 3 images of me, does just that, cropped into squares. But the resulting image is just some random bloke. I don't see any errors in the logs.

Sorry if this is a dumb question and thanks in advance for your time!

**Comment by hben35096** [comment]
It's the same problem, you need to fill in the path in the node in order to read the picture in the path as a reference object...

**Comment by NickDevoctomy** [comment]
Aah okay, thanks!  Much appreciated. It kind of looks like me now 😆

**Comment by hben35096** [comment]
I hope the author can solve this problem, it should only be caused by the error of judging the two input conditions in the node code, maybe don't enter the path for the time being, only read the image input of the image interface, combined with the Make Image List node of Impact-Pack, no matter how much image input is acceptable.


![image](https://github.com/shiimizu/ComfyUI-PhotoMaker/assets/139383150/39a47d08-121e-426c-8e70-5f2734dffa9c)
